[package]
name = "fscheck"
version = "0.1.0"
edition = "2021"

[package.metadata.component]
package = "component:fscheck"

[dependencies]
wit-bindgen-rt = { version = "0.30.0", features = ["bitflags"] }
